// createAdmin.js
// This code was almost entirely generated by ChatGPT (I populated the adminUser object with correct attributes)

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const bcrypt = require('bcrypt');

async function createAdmin() {
  try {
    // Hash password (e.g., "admin123") - change to a secure password in production
    const passwordHash = await bcrypt.hash("admin123", 10);
    
    // Create user with admin role
    const adminUser = await prisma.user.create({
        data: {
          firstName: "Admin",
          lastName: "Pro",
          email: "discordadmin@example.com",
          phoneNumber: "123-456-7890",
          password: passwordHash,
          avatar:  "/avatars/avatar1.png",
          role: "ADMIN",
        }
      });

    console.log("Admin user created:", adminUser);
  } catch (error) {
    console.error("Error creating admin user:", error);
  } finally {
    await prisma.$disconnect();
  }
}

createAdmin();
