# Use the official Python base image
FROM python:3.11-slim

# Install timeout command (part of coreutils)
RUN apt-get update && apt-get install -y coreutils

# Set the working directory inside the container
WORKDIR /scriptorium_docker_files

# Copy any necessary files 
# In this case, this copies all files in the current directory (docker)
COPY . .

# Verify the Python installation
RUN python --version

# Default command to keep the container running (optional)
CMD ["bash"]
